canonical: https://senaite.com/modeling/fhir
fhirVersion: 5.0.0
FSHOnly: true
applyExtensionMetadataToRoot: false
id: senaite.modeling.fhir
name: SENAITE FHIR Models
status: draft
version: "0.1.0"
  
